name: dev_frame
description: Dev Frame

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.12.0+1
  shared_preferences: ^2.0.6 
  flutter_slidable: ^0.6.0
  cupertino_icons: ^1.0.2   
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_intl:
  enabled: true
  class_name: DevFrameLocalization
  main_locale: en

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/loginBack.jpg

